version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    command: ["make", "watch"]
    environment:
      - STORAGE_MIGRATION_DSN=postgres://postgres:postgres@db:5432/crypto
